# @package _global_

algorithm: GAIL
reinforcement:
  discount: 0.97
  target_temperature: -0.5
  polyak_factor: 0.99
imitation:
  absorbing: true
  discriminator:
    hidden_size: 64 
    depth: 1
    activation: relu
    input_dropout: 0.5
    dropout: 0.75
    reward_shaping: false
    subtract_log_policy: false
    reward_function: AIRL
  learning_rate: 0.00003
  weight_decay: 10
  grad_penalty: 1
  spectral_norm: true
  entropy_bonus: 0
  loss_function: BCE
  mixup_alpha: 1
  pos_class_prior: 0.7
  nonnegative_margin: .inf
