# @package _global_

algorithm: RED
imitation:
  discriminator:
    hidden_size: 32
    depth: 1
    activation: relu
    input_dropout: 0
    dropout: 0
  reward_bandwidth_scale: null
  pretraining:
    iterations: 100000
  learning_rate: 0.00003
  weight_decay: 0
